### ISSUE TITLE
org.eclipse.aether.resolution.ArtifactResolutionException

### ISSUE THREAD

**Issue by narkisr** [kipz/clj-gpg-verify#1]
Hi @kipz thank you for releasing this useful plugin, it seems that for some dependencies the following exception is thrown:

```clojure
org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact cc.qbits:knit:pom.asc:1.0.0 in central (https://repo1.maven.org/maven2/)
 at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:423)
    org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:225)
    org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:202)
    org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:257)
    org.kipz.gpg_verify.core$download_artifacts$iter__1088__1092$fn__1093$fn__1094.invoke (core.clj:52)
    org.kipz.gpg_verify.core$download_artifacts$iter__1088__1092$fn__1093.invoke (core.clj:51)
```

The dependencies include:

```clojure
     cc.qbits/knit
     com.rpl/specter
     fogus/minderbinder
     fipp
```

I'm not sure why the code is downloading the dependency from maven central (I would expect it to hit Clojars)

**Comment by kipz** [comment]
@narkisr yeah, I see that sometimes too, though it does seem to work. Does it work for you in this instance too?

**Comment by narkisr** [comment]
Unfortunately no, its failing the verification process with an error

**Comment by kipz** [comment]
@narkisr maybe that error is a bit misleading, but there's no signature in clojars:

https://repo.clojars.org/cc/qbits/knit/1.0.0/

This project is signed, and seems to work with the plugin:

https://repo.clojars.org/org/kipz/clj-gpg-verify/0.1.2/

**Comment by narkisr** [comment]
Yeah it seems like all of the above dependencies didn't sign the jar they uploaded, it would be nice if the tool could warn on this (currently the exception isn't very detailed)

Thanks for the help ill close this issue

**Comment by kipz** [comment]
I agree @narkisr - this could be much nicer! 
I've opened #2 to track this
